INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /admin/comp_settings/527946e7c7df42e19fd2d4337a57002e [POST]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 847, in update_comp_settings
    cursor.execute('''UPDATE factors SET
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 3, and there are 2 supplied.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:18:43] "[35m[1mPOST /admin/comp_settings/527946e7c7df42e19fd2d4337a57002e HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /admin/comp_settings/743a5f3d796249888419d73f4b40a4ca [POST]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 847, in update_comp_settings
    cursor.execute('''UPDATE factors SET
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 3, and there are 2 supplied.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:20:00] "[35m[1mPOST /admin/comp_settings/743a5f3d796249888419d73f4b40a4ca HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:20:55] "[32mPOST /admin/comp_settings/527946e7c7df42e19fd2d4337a57002e HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:20:55] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:21:21] "GET /admin/comp_settings HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:21:25] "[32mPOST /admin/comp_settings/527946e7c7df42e19fd2d4337a57002e HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:21:25] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:21:51] "GET /admin/comp_settings HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:21:54] "[32mPOST /admin/comp_settings/527946e7c7df42e19fd2d4337a57002e HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:21:54] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:21:55] "GET /admin/comp_settings HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:22:47] "GET /admin/comp_settings HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:22:51] "[32mPOST /admin/comp_settings/527946e7c7df42e19fd2d4337a57002e HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:22:51] "GET /admin/comp_settings HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:23:21] "GET /admin/comp_settings HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:23:23] "[35m[1mPOST /admin/comp_settings/527946e7c7df42e19fd2d4337a57002e HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:23:26] "[35m[1mPOST /admin/comp_settings/527946e7c7df42e19fd2d4337a57002e HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:23:29] "[35m[1mPOST /admin/comp_settings/527946e7c7df42e19fd2d4337a57002e HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:23:30] "GET /admin/comp_settings HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:23:35] "[35m[1mPOST /admin/comp_settings/527946e7c7df42e19fd2d4337a57002e HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:24:55] "GET /admin/comp_settings HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:25:46] "GET /admin/comp_settings HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:25:54] "GET /admin/comp_settings HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [05/Sep/2025 23:26:08] "GET /admin/comp_settings HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:42:18] "[33mGET /leaderboards HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:42:23] "[32mGET /leaderboard HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:42:23] "GET /login HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:('[+] User attempting login: username', 'aaa', '|| Password:', 'aaa')
ERROR:app:	|- Login failed
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:42:28] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:42:28] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:42:29] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:42:36] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:42:39] "GET /admin/users HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:42:47] "[31m[1mPOST /generate_users_file HTTP/1.1[0m" 401 -
INFO:app:[+] Generating usernames and passwords
INFO:app:('\t |- Generating n:', '')
ERROR:app:Exception on /generate_users_file [POST]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_basicauth.py", line 108, in wrapper
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 585, in generate_users_file
    for i in range(int(request.form.get("n"))):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:43:04] "[35m[1mPOST /generate_users_file HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:43:10] "[33mGET /users HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:43:14] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:43:16] "GET /admin HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:[!] Invalid post /routes
ERROR:app:400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
INFO:app:[+] Recieved users file
INFO:app:	|- Saving users file
INFO:app:	|- Saved as: tmpUsers
INFO:app:	|- Deleting exsisting users from db
INFO:app:[+] Loading routes from csv: tmpUsers.csv
INFO:app:	|- Csv parsed
INFO:app:	|- Loading to db
INFO:app:('\tExecuting: INSERT INTO users (uuid, username, password) VALUES (', 'ec77620a07d549ab8c2684b6590bea3c', 'aaa', '47bce5c74f589f4867dbd57e9ca9f808', ')')
INFO:app:('\tExecuting: INSERT INTO users (uuid, username, password) VALUES (', '07e82b3658a24f6688324d567f27f883', 'bbb', '08f8e0260c64418510cefb2b06eee5cd', ')')
INFO:app:('\tExecuting: INSERT INTO users (uuid, username, password) VALUES (', '9ccfdc5f39bb4037a1bd8caa74a39b83', 'ccc', '9df62e693988eb4e1e1444ece0578579', ')')
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:43:58] "[32mPOST /admin HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:43:58] "GET /admin HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:44:03] "GET /admin/users HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:44:19] "[32mGET / HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:44:19] "[32mGET /routes HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:44:19] "GET /login HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:('[+] User attempting login: username', 'aaa', '|| Password:', 'aaa')
INFO:app:	|- Login successfull
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:44:22] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:44:22] "GET /routes HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:44:22] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:44:30] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:44:39] "GET /admin HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Recieved routes file
INFO:app:	|- Saving routes file
INFO:app:	|- Saved as: tmpRoutes
INFO:app:	|- Deleting exsisting routes from db
INFO:app:[+] Loading routes from csv: tmpRoutes.csv
INFO:app:	|- Csv parsed
INFO:app:	|- Loading to db
INFO:app:['4', 'tester', 'Difficault', '4a', '5']
INFO:app:['5', 'Overen', 'Borte med bl�sten', '4b', '6']
INFO:app:['6', 'Overen', 'A Walk in the Woods', '4c', '7']
INFO:app:['7', 'Skolev�ggen', 'Easy Peacy', '5a', '5']
INFO:app:['7', 'Skolev�ggen', 'Gungununu', '5a', '3']
INFO:app:['7', 'Elkapitan', 'The Nose', '5a', '4']
INFO:app:['8', 'Det listige hj�rne', 'Mix Ruten', '5b', '5']
INFO:app:['8', 'Elkapitan', 'Skr�Ved', '5b', '6']
INFO:app:['8', 'Overen', 'Madame Butterfly', '5b', '9']
INFO:app:['8', 'Skolev�ggen', 'Aqua Fobia', '5b', '4']
INFO:app:['9', 'Bowlingev�ggen', 'Containertr�f', '5c', '9']
INFO:app:['9', 'Elkapitan', 'Undfangelsen', '5c', '5']
INFO:app:['9', 'Overen', 'For de voksne', '5c', '5']
INFO:app:['9', 'Overen', 'Kanten', '5c', '5']
INFO:app:['9', 'Store gumbas', 'Tetris', '5c', '6']
INFO:app:['10', 'Det listige hj�rne', 'Waikiki Beach', '6a', '4']
INFO:app:['10', 'Elkapitan', 'Space Monkey', '6a', '6']
INFO:app:['10', 'Store gumbas', 'Gaia Love', '6a', '7']
INFO:app:['10', 'Undervejsv�ggen', 'Soltrappen', '6a', '7']
INFO:app:['11', 'Bowlingev�ggen', 'Spare', '6a+', '10']
INFO:app:['11', 'Bowlingev�ggen', 'Strike', '6a+', '7']
INFO:app:['11', 'Det listige hj�rne', 'Fyrtr�et', '6a+', '5']
INFO:app:['11', 'Laustv�ggen', 'Yoni', '6a+', '8']
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:44:47] "[32mPOST /admin HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:44:47] "GET /admin HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:44:50] "GET /routes HTTP/1.1" 200 -
INFO:app:[+] Updating route:37d374c7b3c94a56aac06735c0ea8f2c|2
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:44:56] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:e129e2d961b54213b78ada8d5f7717f5|5
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:44:58] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:c16697a4f70245abb8a95242138b6814|Top
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:44:59] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1024, in leaderboard
    return render_template('leaderboard.html', results=results)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\templates\leaderboard.html", line 225, in top-level template code
    <tr id="{{ route.0 }}">
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 466, in getitem
    return obj[argument]
           ~~~^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'route' is undefined
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:45:08] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:46:19] "GET /leaderboard HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:46:38] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:46:57] "GET /leaderboard HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:46:57] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:47:19] "GET /leaderboard HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:47:19] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 937, in leaderboard
    user_info = cursor.execute("SELECT * FROM climber_id WHERE uuid = \"" + user + "\"").fetchall()
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
TypeError: can only concatenate str (not "tuple") to str
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:52:01] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:52:01] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 937, in leaderboard
    user_info = cursor.execute("SELECT * FROM climber_id WHERE uuid = \"" + user + "\"").fetchall()
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
TypeError: can only concatenate str (not "tuple") to str
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:52:27] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:52:27] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 938, in leaderboard
    user_info = cursor.execute("SELECT * FROM climber_id WHERE uuid = \"" + user + "\"").fetchall()
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
TypeError: can only concatenate str (not "tuple") to str
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:53:06] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:53:06] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 938, in leaderboard
    user_info = cursor.execute("SELECT * FROM climber_id WHERE uuid = \"" + user + "\"").fetchall()
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
TypeError: can only concatenate str (not "tuple") to str
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:53:14] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:53:14] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:54:01] "GET /leaderboard HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:54:01] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: ec77620a07d549ab8c2684b6590bea3c
INFO:app:	|- Gender
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:54:11] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: ec77620a07d549ab8c2684b6590bea3c
INFO:app:	|- team_name
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:54:13] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: ec77620a07d549ab8c2684b6590bea3c
INFO:app:	|- max_flash
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:54:14] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: ec77620a07d549ab8c2684b6590bea3c
INFO:app:	|- dage_i_moselykken
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:54:16] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: ec77620a07d549ab8c2684b6590bea3c
INFO:app:	|- Gender
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:54:17] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:54:20] "GET /leaderboard HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:54:20] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:54:26] "GET /leaderboard HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:54:26] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:54:27] "GET /leaderboard HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 17:54:27] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Updating route:2cf7e0b6aeb042268eb2eefd3d026907|-
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:03:05] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:2cf7e0b6aeb042268eb2eefd3d026907|2
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating in competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:03:06] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:c16697a4f70245abb8a95242138b6814|-
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating in competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:03:07] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:c16697a4f70245abb8a95242138b6814|Top
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating in competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:03:12] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:03:13] "GET /leaderboard HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:03:13] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 939, in leaderboard
    flash_level = user_info[4]
                  ~~~~~~~~~^^^
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:03:47] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:03:47] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 941, in leaderboard
    climbing_days = user_info[5]
                    ~~~~~~~~~^^^
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:04:37] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:04:37] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 985, in leaderboard
    matrix_val = 1 + (route_category[route[5]]-(route_category[flash_level]-1))/factor_coregation
                                     ~~~~~^^^
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:04:58] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:04:58] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 985, in leaderboard
    matrix_val = 1 + (route_category[route[5]]-(route_category[flash_level]-1))/factor_coregation
                                     ~~~~~^^^
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:05:37] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:05:37] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 985, in leaderboard
    matrix_val = 1 + (route_category[route[0][5]]-(route_category[flash_level]-1))/factor_coregation
                                                   ~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '4.a'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:06:20] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:06:20] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:08:46] "GET /routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:08:55] "GET /routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: ec77620a07d549ab8c2684b6590bea3c
INFO:app:	|- max_flash
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:09:00] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1012, in leaderboard
    elif int(r[2].score) >= 2:
             ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'score'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:09:07] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:09:07] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1012, in leaderboard
    elif int(r[0][2].score) >= 2:
             ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'score'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:09:55] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:09:55] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1013, in leaderboard
    elif int(r[2].score) >= 2:
             ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'score'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:10:16] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:10:16] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1013, in leaderboard
    elif int(r[2].score) >= 2:
             ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'score'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:10:36] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:10:36] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1013, in leaderboard
    elif int(r[2].score) >= 2:
             ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'score'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:10:46] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:10:46] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1013, in leaderboard
    elif int(r[2].score) >= 2:
             ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'score'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:10:58] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:10:58] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Creating tables
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:14:44] "GET /admin/users HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:14:51] "POST /admin/users HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:14:55] "POST /admin/users HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:15:08] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:15:09] "GET /admin/users HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:15:16] "POST /admin/users HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:15:18] "POST /admin/users HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:15:18] "POST /admin/users HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:16:26] "POST /admin/users HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:16:36] "GET /admin/users HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:16:39] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:16:45] "GET /admin/users HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:[!] Invalid post /routes
ERROR:app:400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
INFO:app:[+] Recieved users file
INFO:app:	|- Saving users file
INFO:app:	|- Saved as: tmpUsers
INFO:app:	|- Deleting exsisting users from db
INFO:app:[+] Loading routes from csv: tmpUsers.csv
INFO:app:	|- Csv parsed
INFO:app:	|- Loading to db
INFO:app:('\tExecuting: INSERT INTO users (uuid, username, password) VALUES (', 'b9eb05a2add444698d2b2579108cf6f4', 'aaa', '47bce5c74f589f4867dbd57e9ca9f808', ')')
INFO:app:('\tExecuting: INSERT INTO users (uuid, username, password) VALUES (', '99599fdb3eff4138ad3493986e1a2021', 'bbb', '08f8e0260c64418510cefb2b06eee5cd', ')')
INFO:app:('\tExecuting: INSERT INTO users (uuid, username, password) VALUES (', 'ff41555cdadc491d9daec5ae2afde06f', 'ccc', '9df62e693988eb4e1e1444ece0578579', ')')
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:06] "[32mPOST /admin HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:06] "GET /admin HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Recieved routes file
INFO:app:	|- Saving routes file
INFO:app:	|- Saved as: tmpRoutes
INFO:app:	|- Deleting exsisting routes from db
INFO:app:[+] Loading routes from csv: tmpRoutes.csv
INFO:app:	|- Csv parsed
INFO:app:	|- Loading to db
INFO:app:['4', 'tester', 'Difficault', '4a', '5']
INFO:app:['5', 'Overen', 'Borte med bl�sten', '4b', '6']
INFO:app:['6', 'Overen', 'A Walk in the Woods', '4c', '7']
INFO:app:['7', 'Skolev�ggen', 'Easy Peacy', '5a', '5']
INFO:app:['7', 'Skolev�ggen', 'Gungununu', '5a', '3']
INFO:app:['7', 'Elkapitan', 'The Nose', '5a', '4']
INFO:app:['8', 'Det listige hj�rne', 'Mix Ruten', '5b', '5']
INFO:app:['8', 'Elkapitan', 'Skr�Ved', '5b', '6']
INFO:app:['8', 'Overen', 'Madame Butterfly', '5b', '9']
INFO:app:['8', 'Skolev�ggen', 'Aqua Fobia', '5b', '4']
INFO:app:['9', 'Bowlingev�ggen', 'Containertr�f', '5c', '9']
INFO:app:['9', 'Elkapitan', 'Undfangelsen', '5c', '5']
INFO:app:['9', 'Overen', 'For de voksne', '5c', '5']
INFO:app:['9', 'Overen', 'Kanten', '5c', '5']
INFO:app:['9', 'Store gumbas', 'Tetris', '5c', '6']
INFO:app:['10', 'Det listige hj�rne', 'Waikiki Beach', '6a', '4']
INFO:app:['10', 'Elkapitan', 'Space Monkey', '6a', '6']
INFO:app:['10', 'Store gumbas', 'Gaia Love', '6a', '7']
INFO:app:['10', 'Undervejsv�ggen', 'Soltrappen', '6a', '7']
INFO:app:['11', 'Bowlingev�ggen', 'Spare', '6a+', '10']
INFO:app:['11', 'Bowlingev�ggen', 'Strike', '6a+', '7']
INFO:app:['11', 'Det listige hj�rne', 'Fyrtr�et', '6a+', '5']
INFO:app:['11', 'Laustv�ggen', 'Yoni', '6a+', '8']
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:17] "[32mPOST /admin HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:17] "GET /admin HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /routes [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 168, in routes
    for u in user_info[0]:
             ~~~~~~~~~^^^
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:19] "[35m[1mGET /routes HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:22] "[32mGET / HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:22] "GET /login HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:('[+] User attempting login: username', 'aaa', '|| Password:', 'aaa')
INFO:app:	|- Login successfull
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:26] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:26] "GET /routes HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:27] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: b9eb05a2add444698d2b2579108cf6f4
INFO:app:	|- max_flash
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:33] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: b9eb05a2add444698d2b2579108cf6f4
INFO:app:	|- dage_i_moselykken
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:34] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: b9eb05a2add444698d2b2579108cf6f4
INFO:app:	|- Gender
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:35] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:959905f462d24845bf5b04201e4ed8f7|2
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:37] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: b9eb05a2add444698d2b2579108cf6f4
INFO:app:	|- Gender
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:39] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: b9eb05a2add444698d2b2579108cf6f4
INFO:app:	|- team_name
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:42] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:d0cea082fe794dce82a4269c4d5ce38e|2
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:42] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:a0538fdf080844e08476b482f8450075|2
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:44] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:ef60ecc4ca9c4306911e2efa6fcec5b2|Top
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:45] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:f59118ce4ba0451388a78e39bb408bcc|Top
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:47] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1008, in leaderboard
    route_factor = route[6]
                  ~~~~~^^^
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:50] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:17:50] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1008, in leaderboard
    route_factor = route[6]
                  ~~~~~^^^
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:18:39] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:18:39] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:18:51] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:19:23] "GET /admin/routes/959905f462d24845bf5b04201e4ed8f7 HTTP/1.1" 200 -
INFO:app:('[+] Updating route:', '959905f462d24845bf5b04201e4ed8f7', '|', {'action': 'update', 'id': '959905f462d24845bf5b04201e4ed8f7', 'area': 'tester', 'name': 'Difficault', 'grade': '4a', 'max_score': '5', 'factor': '1'})
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:19:26] "[35m[1mPOST /admin/routes/959905f462d24845bf5b04201e4ed8f7 HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:('[+] Updating route:', '959905f462d24845bf5b04201e4ed8f7', '|', {'action': 'update', 'id': '959905f462d24845bf5b04201e4ed8f7', 'area': 'tester', 'name': 'Difficault', 'grade': '4a', 'max_score': '5', 'factor': '1'})
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:20:47] "[35m[1mPOST /admin/routes/959905f462d24845bf5b04201e4ed8f7 HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:20:55] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:21:01] "GET /admin/routes/d0cea082fe794dce82a4269c4d5ce38e HTTP/1.1" 200 -
INFO:app:('[+] Updating route:', 'd0cea082fe794dce82a4269c4d5ce38e', '|', {'action': 'update', 'id': 'd0cea082fe794dce82a4269c4d5ce38e', 'area': 'Det listige hj�rne', 'name': 'Mix Ruten', 'grade': '5b', 'max_score': '5', 'factor': '2'})
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:21:04] "[35m[1mPOST /admin/routes/d0cea082fe794dce82a4269c4d5ce38e HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:21:06] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:21:09] "GET /admin/routes/a0538fdf080844e08476b482f8450075 HTTP/1.1" 200 -
INFO:app:('[+] Updating route:', 'a0538fdf080844e08476b482f8450075', '|', {'action': 'update', 'id': 'a0538fdf080844e08476b482f8450075', 'area': 'Elkapitan', 'name': 'Skr�Ved', 'grade': '5b', 'max_score': '6', 'factor': '2'})
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:21:11] "[35m[1mPOST /admin/routes/a0538fdf080844e08476b482f8450075 HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:21:12] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:21:15] "GET /admin/routes/ef60ecc4ca9c4306911e2efa6fcec5b2 HTTP/1.1" 200 -
INFO:app:('[+] Updating route:', 'ef60ecc4ca9c4306911e2efa6fcec5b2', '|', {'action': 'update', 'id': 'ef60ecc4ca9c4306911e2efa6fcec5b2', 'area': 'Overen', 'name': 'Madame Butterfly', 'grade': '5b', 'max_score': '9', 'factor': '2'})
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:21:19] "[35m[1mPOST /admin/routes/ef60ecc4ca9c4306911e2efa6fcec5b2 HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1009, in leaderboard
    route_factor = route[6]
                  ~~~~~^^^
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:21:21] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 18:21:21] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1009, in leaderboard
    route_factor = route[6]
                  ~~~~~^^^
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 21:46:07] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 21:46:07] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1009, in leaderboard
    route_factor = route[6]
                  ~~~~~^^^
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:02:08] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:02:08] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1010, in leaderboard
    route_factor = route[6]
                  ~~~~~^^^
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:02:58] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:02:58] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1017, in leaderboard
    elif int(r[2].score) >= 2:
             ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'score'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:03:26] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:03:26] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1018, in leaderboard
    elif int(route_score) >= 2:
         ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Difficault'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:04:02] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:04:02] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1018, in leaderboard
    elif route_score >= 2:
         ^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'str' and 'int'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:04:42] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:04:42] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1018, in leaderboard
    elif int(route_score) >= 2:
         ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Difficault'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:05:03] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:05:03] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1018, in leaderboard
    elif int(route_score) >= 2:
         ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '09/08/2025, 18:17:37'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:06:01] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:06:01] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1024, in leaderboard
    route_score = route_score + route_point
                  ~~~~~~~~~~~~^~~~~~~~~~~~~
TypeError: can only concatenate str (not "float") to str
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:06:23] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:06:23] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: b9eb05a2add444698d2b2579108cf6f4
INFO:app:	|- max_flash
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:07:00] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: b9eb05a2add444698d2b2579108cf6f4
INFO:app:	|- dage_i_moselykken
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:07:02] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1018, in leaderboard
    elif int(route_score) >= 2:
         ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Top'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:08:08] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:08:08] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:08:35] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:08:38] "GET /admin/routes/0adb3a76a989458c926ccecf9c7c4587 HTTP/1.1" 200 -
INFO:app:('[+] Updating route:', '0adb3a76a989458c926ccecf9c7c4587', '|', {'action': 'update', 'id': '0adb3a76a989458c926ccecf9c7c4587', 'area': 'Overen', 'name': 'A Walk in the Woods', 'grade': '4c', 'max_score': '7', 'factor': '23'})
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:08:45] "[35m[1mPOST /admin/routes/0adb3a76a989458c926ccecf9c7c4587 HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:0adb3a76a989458c926ccecf9c7c4587|Top
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:08:52] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1018, in leaderboard
    elif int(route_score) >= 2:
         ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Top'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:08:55] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:08:55] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1018, in leaderboard
    elif int(route_score) >= 2:
         ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Top'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:10:15] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:10:15] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:11:11] "GET /routes HTTP/1.1" 200 -
INFO:app:[+] Updating route:0adb3a76a989458c926ccecf9c7c4587|6
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating in competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:11:16] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:0adb3a76a989458c926ccecf9c7c4587|Top
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating in competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:11:18] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:0adb3a76a989458c926ccecf9c7c4587|Top
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating in competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:11:24] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1018, in leaderboard
    elif int(route_score) >= 2:
         ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Top'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:11:29] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:11:29] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:13:18] "GET /routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1018, in leaderboard
    elif int(route_score) >= 2:
         ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Top'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:13:30] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:13:30] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:13:49] "[32mGET /logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:13:49] "GET /login HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:('[+] User attempting login: username', 'bbb', '|| Password:', 'bbb')
INFO:app:	|- Login successfull
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:13:52] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:13:52] "GET /routes HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:13:53] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:14:10] "[32mGET /logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:14:10] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:14:11] "GET /login HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:('[+] User attempting login: username', 'ccc', '|| Password:', 'ccc')
INFO:app:	|- Login successfull
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:14:15] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:14:15] "GET /routes HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:14:16] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1018, in leaderboard
    elif int(route_score) >= 2:
         ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Top'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:14:28] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:14:28] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1018, in leaderboard
    elif int(route_score) >= 2:
         ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Top'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:14:56] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:14:56] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Creating tables
ERROR:app:Exception on /admin/routes/0adb3a76a989458c926ccecf9c7c4587 [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 683, in admin_routes_edit_page
    return render_template('admin/routes_edit.html', route=route)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\templates\admin\routes_edit.html", line 5, in top-level template code
    <h2 style="margin-top: 0px; color: lime;">Edit Route {{ route[0].0 }} - {{ route[0].2 }}</h2>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 466, in getitem
    return obj[argument]
           ~~~^^^^^^^^^^
jinja2.exceptions.UndefinedError: list object has no element 0
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:15:10] "[35m[1mGET /admin/routes/0adb3a76a989458c926ccecf9c7c4587 HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /admin/routes/0adb3a76a989458c926ccecf9c7c4587 [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 683, in admin_routes_edit_page
    return render_template('admin/routes_edit.html', route=route)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\templates\admin\routes_edit.html", line 5, in top-level template code
    <h2 style="margin-top: 0px; color: lime;">Edit Route {{ route[0].0 }} - {{ route[0].2 }}</h2>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 466, in getitem
    return obj[argument]
           ~~~^^^^^^^^^^
jinja2.exceptions.UndefinedError: list object has no element 0
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:15:17] "[35m[1mGET /admin/routes/0adb3a76a989458c926ccecf9c7c4587 HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:15:20] "[33mGET /admin/routes/ HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:15:22] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:('[+] Adding new route;', <bound method MultiDict.values of ImmutableMultiDict([])>)
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:16:26] "[32mPOST /admin/routes HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:16:26] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:16:30] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:16:33] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:16:34] "GET /admin/users HTTP/1.1" 200 -
INFO:app:[+] Generating usernames and passwords
INFO:app:('\t |- Generating n:', '')
ERROR:app:Exception on /generate_users_file [POST]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_basicauth.py", line 108, in wrapper
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 585, in generate_users_file
    for i in range(int(request.form.get("n"))):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:16:36] "[35m[1mPOST /generate_users_file HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:[!] Invalid post /routes
ERROR:app:400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
INFO:app:[+] Recieved users file
INFO:app:	|- Saving users file
INFO:app:	|- Saved as: tmpUsers
INFO:app:	|- Deleting exsisting users from db
INFO:app:[+] Loading routes from csv: tmpUsers.csv
INFO:app:	|- Csv parsed
INFO:app:	|- Loading to db
INFO:app:('\tExecuting: INSERT INTO users (uuid, username, password) VALUES (', '5b551565e4d04de1a5d0847d0ee077fe', 'aaa', '47bce5c74f589f4867dbd57e9ca9f808', ')')
INFO:app:('\tExecuting: INSERT INTO users (uuid, username, password) VALUES (', '1a2cb3c91cc24ea19e622aca1f63a762', 'bbb', '08f8e0260c64418510cefb2b06eee5cd', ')')
INFO:app:('\tExecuting: INSERT INTO users (uuid, username, password) VALUES (', '41f7695c86cd47d3a110daae05cd4f25', 'ccc', '9df62e693988eb4e1e1444ece0578579', ')')
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:16:45] "[32mPOST /admin HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:16:45] "GET /admin HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:16:50] "GET /admin/users HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:16:52] "GET /admin/users HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:16:55] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:('[+] Adding new route;', <bound method MultiDict.values of ImmutableMultiDict([])>)
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:17:15] "[32mPOST /admin/routes HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:17:15] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:17:38] "GET /admin HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Recieved routes file
INFO:app:	|- Saving routes file
INFO:app:	|- Saved as: tmpRoutes
INFO:app:	|- Deleting exsisting routes from db
INFO:app:[+] Loading routes from csv: tmpRoutes.csv
INFO:app:	|- Csv parsed
INFO:app:	|- Loading to db
INFO:app:['4', 'tester', 'Difficault', '4a', '5']
INFO:app:['5', 'Overen', 'Borte med bl�sten', '4b', '6']
INFO:app:['6', 'Overen', 'A Walk in the Woods', '4c', '7']
INFO:app:['7', 'Skolev�ggen', 'Easy Peacy', '5a', '5']
INFO:app:['7', 'Skolev�ggen', 'Gungununu', '5a', '3']
INFO:app:['7', 'Elkapitan', 'The Nose', '5a', '4']
INFO:app:['8', 'Det listige hj�rne', 'Mix Ruten', '5b', '5']
INFO:app:['8', 'Elkapitan', 'Skr�Ved', '5b', '6']
INFO:app:['8', 'Overen', 'Madame Butterfly', '5b', '9']
INFO:app:['8', 'Skolev�ggen', 'Aqua Fobia', '5b', '4']
INFO:app:['9', 'Bowlingev�ggen', 'Containertr�f', '5c', '9']
INFO:app:['9', 'Elkapitan', 'Undfangelsen', '5c', '5']
INFO:app:['9', 'Overen', 'For de voksne', '5c', '5']
INFO:app:['9', 'Overen', 'Kanten', '5c', '5']
INFO:app:['9', 'Store gumbas', 'Tetris', '5c', '6']
INFO:app:['10', 'Det listige hj�rne', 'Waikiki Beach', '6a', '4']
INFO:app:['10', 'Elkapitan', 'Space Monkey', '6a', '6']
INFO:app:['10', 'Store gumbas', 'Gaia Love', '6a', '7']
INFO:app:['10', 'Undervejsv�ggen', 'Soltrappen', '6a', '7']
INFO:app:['11', 'Bowlingev�ggen', 'Spare', '6a+', '10']
INFO:app:['11', 'Bowlingev�ggen', 'Strike', '6a+', '7']
INFO:app:['11', 'Det listige hj�rne', 'Fyrtr�et', '6a+', '5']
INFO:app:['11', 'Laustv�ggen', 'Yoni', '6a+', '8']
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:17:44] "[32mPOST /admin HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:17:44] "GET /admin HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:17:55] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:17:59] "GET /admin/routes/6a2b4365c0ea4087b8c8caa0540efbbc HTTP/1.1" 200 -
INFO:app:('[+] Updating route:', '6a2b4365c0ea4087b8c8caa0540efbbc', '|', {'action': 'update', 'id': '6a2b4365c0ea4087b8c8caa0540efbbc', 'area': 'Overen', 'name': 'A Walk in the Woods', 'grade': '4c', 'max_score': '7', 'factor': '23'})
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:03] "[35m[1mPOST /admin/routes/6a2b4365c0ea4087b8c8caa0540efbbc HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:05] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:08] "GET /admin/routes/d360a09c161046a5a8ca3aeb44ebc2a7 HTTP/1.1" 200 -
INFO:app:('[+] Updating route:', 'd360a09c161046a5a8ca3aeb44ebc2a7', '|', {'action': 'update', 'id': 'd360a09c161046a5a8ca3aeb44ebc2a7', 'area': 'Laustv�ggen', 'name': 'Yoni', 'grade': '6a+', 'max_score': '8', 'factor': '28'})
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:13] "[35m[1mPOST /admin/routes/d360a09c161046a5a8ca3aeb44ebc2a7 HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1037, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:17] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:17] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:23] "[32mGET /logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:23] "GET /login HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:('[+] User attempting login: username', 'aaa', '|| Password:', 'aaa')
INFO:app:	|- Login successfull
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:26] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:26] "GET /routes HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:26] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:app:[+] Updating route:6a2b4365c0ea4087b8c8caa0540efbbc|Top
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:37] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:d360a09c161046a5a8ca3aeb44ebc2a7|Top
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:41] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: 5b551565e4d04de1a5d0847d0ee077fe
INFO:app:	|- max_flash
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:51] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: 5b551565e4d04de1a5d0847d0ee077fe
INFO:app:	|- dage_i_moselykken
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:53] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: 5b551565e4d04de1a5d0847d0ee077fe
INFO:app:	|- Gender
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:55] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1018, in leaderboard
    elif int(route_score) >= 2:
         ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Top'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:58] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:18:58] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1040, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:21:22] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:21:22] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1038, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:22:16] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:22:17] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1038, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:24:12] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:24:12] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1038, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:26:14] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:26:14] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1038, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:26:18] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:26:18] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1039, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:36:35] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1060, in leaderboard
    print("\t|-> Flash:", f)
                          ^
NameError: name 'f' is not defined
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:41:49] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1040, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:42:25] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1040, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:43:55] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:53:32] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:('[+] Adding new route;', <bound method MultiDict.values of ImmutableMultiDict([('area', '1'), ('name', 'Den lille diedre'), ('grade', '3g'), ('max_score', '4'), ('factor', '20')])>)
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:54:40] "[32mPOST /admin/routes HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:54:40] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:54:47] "GET /routes HTTP/1.1" 200 -
INFO:app:[+] Updating route:78eafcbe14824d2e90d24c8bb503330c|2
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:54:51] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1021, in leaderboard
    route_point = route_factor * 0.8 / route_max
                  ~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:55:05] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:56:14] "GET /admin/routes/78eafcbe14824d2e90d24c8bb503330c HTTP/1.1" 200 -
INFO:app:('[+] Updating route:', '78eafcbe14824d2e90d24c8bb503330c', '|', {'action': 'update', 'id': '78eafcbe14824d2e90d24c8bb503330c', 'area': '1', 'name': 'Den lille diedre', 'grade': '3g', 'max_score': '4', 'factor': '20'})
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:56:25] "[35m[1mPOST /admin/routes/78eafcbe14824d2e90d24c8bb503330c HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:56:27] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:56:31] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1040, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 22:56:49] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1041, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:01:16] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1041, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:01:40] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1041, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:01:58] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1041, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:02:05] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1041, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:03:48] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1041, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:06:14] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:('[+] Adding new route;', <bound method MultiDict.values of ImmutableMultiDict([('area', '1'), ('name', 'margurit ruten'), ('grade', '4a'), ('max_score', '4'), ('factor', '')])>)
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:09:42] "[32mPOST /admin/routes HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:09:42] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:09:45] "GET /admin/routes/a653091bbf2a4270ab4e7377a1dfa8d7 HTTP/1.1" 200 -
INFO:app:('[+] Updating route:', 'a653091bbf2a4270ab4e7377a1dfa8d7', '|', {'action': 'update', 'id': 'a653091bbf2a4270ab4e7377a1dfa8d7', 'area': '1', 'name': 'margurit ruten', 'grade': '4a', 'max_score': '4', 'factor': '21'})
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:09:53] "[35m[1mPOST /admin/routes/a653091bbf2a4270ab4e7377a1dfa8d7 HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:78eafcbe14824d2e90d24c8bb503330c|None
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating in competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:10:01] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:10:04] "GET /routes HTTP/1.1" 200 -
INFO:app:[+] Updating route:a653091bbf2a4270ab4e7377a1dfa8d7|3
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:10:09] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1020, in leaderboard
    elif int(route_score) >= 2:
         ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'None'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:10:11] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1020, in leaderboard
    elif int(route_score) >= 2:
         ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'None'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:10:50] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:11:03] "GET /routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:11:11] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:11:15] "GET /admin/routes/a653091bbf2a4270ab4e7377a1dfa8d7 HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1042, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:12:13] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 937, in leaderboard
    leaderboard.append([user[1], ""])
                        ~~~~^^^
IndexError: tuple index out of range
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:19:38] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 937, in leaderboard
    leaderboard[i] = [user[1], ""]
                      ~~~~^^^
IndexError: tuple index out of range
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:20:35] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 941, in leaderboard
    leaderboard[i] = [user_info[0][1], ""]
    ~~~~~~~~~~~^^^
IndexError: list assignment index out of range
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:21:28] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1029, in leaderboard
    if int(climbing_days) <= int(key):
       ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:21:52] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1062, in leaderboard
    if int(route_category[flash_level]) < int(key):
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: None
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:22:55] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1061, in leaderboard
    if route_category[flash_level] == 'None':
       ~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: None
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:23:48] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1061, in leaderboard
    if not route_category[flash_level]:
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: None
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:24:15] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:24:36] "GET /leaderboard HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: 5b551565e4d04de1a5d0847d0ee077fe
INFO:app:	|- Gender
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:24:50] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: 5b551565e4d04de1a5d0847d0ee077fe
INFO:app:	|- team_name
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:24:51] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:24:54] "GET /leaderboard HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:24:59] "[32mGET /logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:24:59] "GET /login HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:('[+] User attempting login: username', 'bbb', '|| Password:', 'bbb')
INFO:app:	|- Login successfull
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:25:04] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:25:04] "GET /routes HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:25:04] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: 1a2cb3c91cc24ea19e622aca1f63a762
INFO:app:	|- Gender
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:25:11] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: 1a2cb3c91cc24ea19e622aca1f63a762
INFO:app:	|- team_name
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:25:11] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: 1a2cb3c91cc24ea19e622aca1f63a762
INFO:app:	|- team_name
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:25:13] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: 1a2cb3c91cc24ea19e622aca1f63a762
INFO:app:	|- max_flash
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:25:15] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: 1a2cb3c91cc24ea19e622aca1f63a762
INFO:app:	|- dage_i_moselykken
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:25:17] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Updating user: 1a2cb3c91cc24ea19e622aca1f63a762
INFO:app:	|- Gender
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:25:18] "[35m[1mPOST /climber_id HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:cb461ff6a8b44dd39f6e6ffa9918fb1d|Top
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:25:22] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:6a2b4365c0ea4087b8c8caa0540efbbc|-
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:25:25] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:d360a09c161046a5a8ca3aeb44ebc2a7|-
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:25:30] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:78eafcbe14824d2e90d24c8bb503330c|-
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:25:31] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:a653091bbf2a4270ab4e7377a1dfa8d7|-
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:25:32] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Updating route:f607f9a10c87456298f06ed4c484aaa1|Top
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Inserting into competition
INFO:app:	|- Commiting to database
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:25:34] "[35m[1mPOST /route_post HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1007, in leaderboard
    route_point = route_factor * matrix_val
                  ~~~~~~~~~~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:25:37] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /leaderboard [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 1009, in leaderboard
    route_point = route_factor * matrix_val
                  ~~~~~~~~~~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:26:17] "[35m[1mGET /leaderboard HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:27:10] "GET /admin/users HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:27:11] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:27:16] "GET /admin/routes/f607f9a10c87456298f06ed4c484aaa1 HTTP/1.1" 200 -
INFO:app:('[+] Updating route:', 'f607f9a10c87456298f06ed4c484aaa1', '|', {'action': 'update', 'id': 'f607f9a10c87456298f06ed4c484aaa1', 'area': 'Elkapitan', 'name': 'Space Monkey', 'grade': '6a', 'max_score': '6', 'factor': '23'})
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:27:20] "[35m[1mPOST /admin/routes/f607f9a10c87456298f06ed4c484aaa1 HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:27:21] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:27:24] "GET /admin/routes/cb461ff6a8b44dd39f6e6ffa9918fb1d HTTP/1.1" 200 -
INFO:app:('[+] Updating route:', 'cb461ff6a8b44dd39f6e6ffa9918fb1d', '|', {'action': 'update', 'id': 'cb461ff6a8b44dd39f6e6ffa9918fb1d', 'area': 'Skolev�ggen', 'name': 'Easy Peacy', 'grade': '5a', 'max_score': '5', 'factor': '12'})
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:27:29] "[35m[1mPOST /admin/routes/cb461ff6a8b44dd39f6e6ffa9918fb1d HTTP/1.1[0m" 204 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:27:30] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [08/Sep/2025 23:27:35] "GET /leaderboard HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:39:45] "GET /admin/routes HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:39:50] "GET /admin HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:40:02] "GET /routes HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:40:06] "[32mGET /logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:40:06] "GET /login HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:('[+] User attempting login: username', 'ccc', '|| Password:', 'ccc')
INFO:app:	|- Login successfull
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:40:10] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:40:10] "GET /routes HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:40:10] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Creating tables
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /routes [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 168, in routes
    for u in user_info[0]:
             ~~~~~~~~~^^^
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:40:22] "[35m[1mGET /routes HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:40:24] "GET /admin HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:[+] Recieved routes file
INFO:app:	|- Saving routes file
INFO:app:	|- Saved as: tmpRoutes
INFO:app:	|- Deleting exsisting routes from db
INFO:app:[+] Loading routes from csv: tmpRoutes.csv
INFO:app:	|- Csv parsed
INFO:app:	|- Loading to db
INFO:app:['4', 'tester', 'Difficault', '4a', '5']
INFO:app:['5', 'Overen', 'Borte med bl�sten', '4b', '6']
INFO:app:['6', 'Overen', 'A Walk in the Woods', '4c', '7']
INFO:app:['7', 'Skolev�ggen', 'Easy Peacy', '5a', '5']
INFO:app:['7', 'Skolev�ggen', 'Gungununu', '5a', '3']
INFO:app:['7', 'Elkapitan', 'The Nose', '5a', '4']
INFO:app:['8', 'Det listige hj�rne', 'Mix Ruten', '5b', '5']
INFO:app:['8', 'Elkapitan', 'Skr�Ved', '5b', '6']
INFO:app:['8', 'Overen', 'Madame Butterfly', '5b', '9']
INFO:app:['8', 'Skolev�ggen', 'Aqua Fobia', '5b', '4']
INFO:app:['9', 'Bowlingev�ggen', 'Containertr�f', '5c', '9']
INFO:app:['9', 'Elkapitan', 'Undfangelsen', '5c', '5']
INFO:app:['9', 'Overen', 'For de voksne', '5c', '5']
INFO:app:['9', 'Overen', 'Kanten', '5c', '5']
INFO:app:['9', 'Store gumbas', 'Tetris', '5c', '6']
INFO:app:['10', 'Det listige hj�rne', 'Waikiki Beach', '6a', '4']
INFO:app:['10', 'Elkapitan', 'Space Monkey', '6a', '6']
INFO:app:['10', 'Store gumbas', 'Gaia Love', '6a', '7']
INFO:app:['10', 'Undervejsv�ggen', 'Soltrappen', '6a', '7']
INFO:app:['11', 'Bowlingev�ggen', 'Spare', '6a+', '10']
INFO:app:['11', 'Bowlingev�ggen', 'Strike', '6a+', '7']
INFO:app:['11', 'Det listige hj�rne', 'Fyrtr�et', '6a+', '5']
INFO:app:['11', 'Laustv�ggen', 'Yoni', '6a+', '8']
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:40:40] "[32mPOST /admin HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:40:40] "GET /admin HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:[!] Invalid post /routes
ERROR:app:400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
INFO:app:[+] Recieved users file
INFO:app:	|- Saving users file
INFO:app:	|- Saved as: tmpUsers
INFO:app:	|- Deleting exsisting users from db
INFO:app:[+] Loading routes from csv: tmpUsers.csv
INFO:app:	|- Csv parsed
INFO:app:	|- Loading to db
INFO:app:('\tExecuting: INSERT INTO users (uuid, username, password) VALUES (', 'c969973f07ef4c6387a34108fb3a3be9', 'aaa', '47bce5c74f589f4867dbd57e9ca9f808', ')')
INFO:app:('\tExecuting: INSERT INTO users (uuid, username, password) VALUES (', 'bb9f6bd422cf45cea7d138a7468eac8a', 'bbb', '08f8e0260c64418510cefb2b06eee5cd', ')')
INFO:app:('\tExecuting: INSERT INTO users (uuid, username, password) VALUES (', '513415a98cf047448ef2d47ce3ac69f4', 'ccc', '9df62e693988eb4e1e1444ece0578579', ')')
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:40:48] "[32mPOST /admin HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:40:48] "GET /admin HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /routes [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 168, in routes
    for u in user_info[0]:
             ~~~~~~~~~^^^
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:40:52] "[35m[1mGET /routes HTTP/1.1[0m" 500 -
INFO:app:[+] Database Sqlite3.db loaded.
ERROR:app:Exception on /routes [GET]
Traceback (most recent call last):
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ham-d\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgrammingProjects\BotR_ClimbingCompetition\app.py", line 168, in routes
    for u in user_info[0]:
             ~~~~~~~~~^^^
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:40:55] "[35m[1mGET /routes HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:40:58] "GET /login HTTP/1.1" 200 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:app:('[+] User attempting login: username', 'aaa', '|| Password:', 'aaa')
INFO:app:	|- Login successfull
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:41:02] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:app:[+] Database Sqlite3.db loaded.
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:41:02] "GET /routes HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Sep/2025 20:41:03] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
